import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/src/shared/providers/QueryProvider";
import { ColorModeComponent } from "@/src/shared/components/ColorModeComponent";
import { NavBarComponent } from "@/src/shared/components/NavBarComponent";
import { SideMenuComponent } from "@/src/shared/components/SideMenuComponent";
import { ThemeProvider } from "@/src/shared/providers/ThemeProvider";
import { Gem } from "lucide-react";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const actualYear = new Date().getFullYear();

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <SwalConfirmProvider> */}
          <header className="flex justify-between p-2 border-b">
            <div className="flex items-center gap-2">
              <h2 className="ml-4 px-2 text-center">
                <Gem />
              </h2>

              <NavBarComponent />
            </div>
            <div className="flex items-center px-2 gap-2">
              <ColorModeComponent />
              <SideMenuComponent />
            </div>
          </header>

          <QueryProvider>
            <main className="flex-1">{children}</main>
          </QueryProvider>

          <Toaster position="top-right" richColors closeButton />

          <footer className="flex items-center p-2 border-t">
            <small>
              Desenvolvido por <b>Roger Pelissoni</b> ©{actualYear}
            </small>
          </footer>
          {/* </SwalConfirmProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
