import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import { NotificationBell } from "@/src/modules/notification/NotificationBell";
import { ColorModeComponent } from "@/src/shared/components/ColorModeComponent";
import { NavBarComponent } from "@/src/shared/components/NavBarComponent";
import { SideMenuComponent } from "@/src/shared/components/SideMenuComponent";
import { QueryProvider } from "@/src/shared/providers/QueryProvider";
import { StompProvider } from "@/src/shared/providers/StompProvider";
import { ThemeProvider } from "@/src/shared/providers/ThemeProvider";
import { cn } from "@/src/shared/utils/util";
import { Gem, Settings } from "lucide-react";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const actualYear = new Date().getFullYear();

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={cn(geist.className, "antialiased min-h-screen flex flex-col")}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {/* <SwalConfirmProvider> */}
          <QueryProvider>
            <StompProvider>
              <header className="flex justify-between p-2 border-b">
                <div className="flex items-center gap-2">
                  <h2 className="ml-4 px-2 text-center">
                    <Gem />
                  </h2>

                  <NavBarComponent />
                </div>
                <div className="flex items-center px-2 gap-2">
                  <NotificationBell />

                  <Button variant="outline" size="icon" asChild>
                    <Link href="/dashboard/settings">
                      <Settings className="h-[1.2rem] w-[1.2rem]" />
                      <span className="sr-only">Configurações</span>
                    </Link>
                  </Button>

                  <ColorModeComponent />
                  <SideMenuComponent />
                </div>
              </header>

              <main className="flex-1">{children}</main>
            </StompProvider>
          </QueryProvider>

          <Toaster position="top-right" richColors closeButton />

          <footer className="flex items-center p-2 border-t">
            <small>
              Desenvolvido por <b>Roger Pelissoni</b> ©{actualYear}
            </small>
          </footer>
          {/* </SwalConfirmProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
